/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef, useEffect } from 'react';
import { 
  Shield, 
  Key, 
  Globe, 
  Database, 
  Download, 
  Upload, 
  Bell, 
  Smartphone, 
  CheckCircle, 
  AlertTriangle, 
  ChevronRight,
  Sparkles,
  Signature,
  FileText,
  UserCheck
} from 'lucide-react';
import { Member, ChitGroup, BiddingDraw, Installment } from '../types';

interface SettingsManagerProps {
  members: Member[];
  groups: ChitGroup[];
  draws: BiddingDraw[];
  installments: Installment[];
  onImportData: (data: { members: Member[]; groups: ChitGroup[]; draws: BiddingDraw[]; installments: Installment[] }) => void;
  language: string;
  onLanguageChange: (lang: string) => void;
  securityPin: string;
  onSecurityPinChange: (pin: string) => void;
}

export default function SettingsManager({
  members,
  groups,
  draws,
  installments,
  onImportData,
  language,
  onLanguageChange,
  securityPin,
  onSecurityPinChange
}: SettingsManagerProps) {
  const [pinInput, setPinInput] = useState(securityPin);
  const [pinStatus, setPinStatus] = useState<string | null>(null);
  const [isPinModalOpen, setIsPinModalOpen] = useState(false);
  const [simulatedReminderStatus, setSimulatedReminderStatus] = useState<string | null>(null);

  // Signature canvas states
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [isDrawing, setIsDrawing] = useState(false);
  const [signatureSaved, setSignatureSaved] = useState(false);

  useEffect(() => {
    // Try to load any previously stored signature
    const savedSig = localStorage.getItem('chitmaster_signature');
    if (savedSig) {
      setSignatureSaved(true);
    }
  }, []);

  // Back up data to JSON
  const handleExportBackup = () => {
    const backupData = {
      version: '1.0.0',
      timestamp: new Date().toISOString(),
      data: { members, groups, draws, installments }
    };
    const blob = new Blob([JSON.stringify(backupData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `chitmaster_pro_backup_${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Restore data from JSON
  const handleImportBackup = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target?.result as string);
        if (parsed && parsed.data && parsed.data.members && parsed.data.groups) {
          onImportData(parsed.data);
          alert('Database restored successfully! All ledgers, groups, and members synced.');
        } else {
          alert('Invalid backup file format. Make sure it was generated by ChitMaster Pro.');
        }
      } catch (err) {
        alert('Failed to parse backup file. Please ensure the file is valid JSON.');
      }
    };
    reader.readAsText(file);
  };

  // Set Security PIN
  const handleSavePin = (e: React.FormEvent) => {
    e.preventDefault();
    if (pinInput.length === 4 && /^\d+$/.test(pinInput)) {
      onSecurityPinChange(pinInput);
      setPinStatus('PIN code saved successfully!');
      setTimeout(() => setPinStatus(null), 3000);
    } else if (pinInput === '') {
      onSecurityPinChange('');
      setPinStatus('PIN security disabled.');
      setTimeout(() => setPinStatus(null), 3000);
    } else {
      setPinStatus('Error: PIN must be exactly 4 numeric digits.');
      setTimeout(() => setPinStatus(null), 3500);
    }
  };

  // Simulated Reminder Service
  const handleTriggerSimulatedReminder = (type: 'whatsapp' | 'sms') => {
    setSimulatedReminderStatus(`Triggering dynamic ${type === 'whatsapp' ? 'WhatsApp' : 'SMS'} reminders to outstanding members...`);
    setTimeout(() => {
      const pendingCount = installments.filter(i => i.status === 'overdue').length;
      if (pendingCount > 0) {
        setSimulatedReminderStatus(`Success: Simulated ${type === 'whatsapp' ? 'WhatsApp QR' : 'SMS'} reminders sent to ${pendingCount} outstanding members successfully!`);
      } else {
        setSimulatedReminderStatus(`Clear: All members are fully paid up. No outstanding notifications needed.`);
      }
      setTimeout(() => setSimulatedReminderStatus(null), 5000);
    }, 1500);
  };

  // Signature canvas handlers
  const startDrawing = (e: React.MouseEvent<HTMLCanvasElement> | React.TouchEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    ctx.strokeStyle = '#312e81';
    ctx.lineWidth = 3;
    ctx.lineCap = 'round';

    const rect = canvas.getBoundingClientRect();
    const x = ('touches' in e) ? e.touches[0].clientX - rect.left : e.clientX - rect.left;
    const y = ('touches' in e) ? e.touches[0].clientY - rect.top : e.clientY - rect.top;

    ctx.beginPath();
    ctx.moveTo(x, y);
    setIsDrawing(true);
  };

  const draw = (e: React.MouseEvent<HTMLCanvasElement> | React.TouchEvent<HTMLCanvasElement>) => {
    if (!isDrawing) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const rect = canvas.getBoundingClientRect();
    const x = ('touches' in e) ? e.touches[0].clientX - rect.left : e.clientX - rect.left;
    const y = ('touches' in e) ? e.touches[0].clientY - rect.top : e.clientY - rect.top;

    ctx.lineTo(x, y);
    ctx.stroke();
  };

  const stopDrawing = () => {
    setIsDrawing(false);
  };

  const clearCanvas = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    localStorage.removeItem('chitmaster_signature');
    setSignatureSaved(false);
  };

  const saveSignature = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const dataUrl = canvas.toDataURL('image/png');
    localStorage.setItem('chitmaster_signature', dataUrl);
    setSignatureSaved(true);
    alert('Authorized organizer signature saved for printable PDF receipts!');
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 text-left animate-fade-in" id="settings-manager-container">
      {/* Settings Options Column */}
      <div className="lg:col-span-2 space-y-6">
        
        {/* Core Settings Form */}
        <div className="bg-white border border-slate-100 rounded-2xl p-6 shadow-xs space-y-6">
          <div className="border-b border-slate-50 pb-4">
            <h3 className="font-bold text-slate-900 text-lg flex items-center gap-2">
              <Smartphone className="w-5 h-5 text-indigo-600" />
              ChitMaster Pro Settings
            </h3>
            <p className="text-xs text-slate-500">Configure language localizations, custom interest multipliers, security locks, and digital signatures.</p>
          </div>

          <div className="space-y-6">
            
            {/* 1. Language Localizations (Multilingual) */}
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
                <Globe className="w-4 h-4 text-indigo-500" />
                Select Localization Language
              </label>
              <p className="text-xs text-slate-500">Choose English, Telugu (తెలుగు), or Kannada (ಕನ್ನಡ) for UI elements, statistics, and reports</p>
              <div className="grid grid-cols-3 gap-3 pt-1">
                {[
                  { code: 'en', label: 'English', detail: 'UK/US standard' },
                  { code: 'te', label: 'తెలుగు', detail: 'Andhra/Telangana' },
                  { code: 'kn', label: 'ಕನ್ನಡ', detail: 'Karnataka' },
                ].map(lang => (
                  <button
                    key={lang.code}
                    onClick={() => onLanguageChange(lang.code)}
                    className={`p-3.5 rounded-xl border text-left transition-all cursor-pointer ${
                      language === lang.code
                        ? 'border-indigo-600 bg-indigo-50/50 ring-2 ring-indigo-500/10'
                        : 'border-slate-100 bg-slate-50/50 hover:bg-slate-50 hover:border-slate-200'
                    }`}
                  >
                    <p className="text-xs font-bold text-slate-800">{lang.label}</p>
                    <span className="text-[10px] text-slate-400 font-medium font-mono block mt-0.5">{lang.detail}</span>
                  </button>
                ))}
              </div>
            </div>

            <hr className="border-slate-100" />

            {/* 2. PIN Lock Security Option */}
            <div className="space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
                  <Shield className="w-4 h-4 text-indigo-500" />
                  App PIN Lock Protection
                </label>
                <p className="text-xs text-slate-500">Secure your offline chit ledgers behind a 4-digit numeric PIN lock screen on startup</p>
              </div>

              <form onSubmit={handleSavePin} className="flex flex-col sm:flex-row gap-3 items-end">
                <div className="space-y-1 text-left w-full sm:w-auto">
                  <span className="text-[10px] font-bold text-slate-400 font-mono">4-DIGIT PIN CODE</span>
                  <input
                    type="password"
                    maxLength={4}
                    placeholder="Enter numeric PIN"
                    value={pinInput}
                    onChange={(e) => setPinInput(e.target.value.replace(/\D/g, ''))}
                    className="px-3.5 py-2.5 bg-slate-50 border border-slate-100 rounded-xl text-xs w-full sm:w-48 font-mono focus:outline-hidden focus:border-indigo-500"
                  />
                </div>
                <button
                  type="submit"
                  className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-2.5 px-6 rounded-xl text-xs cursor-pointer transition-colors shrink-0 w-full sm:w-auto"
                >
                  {securityPin ? 'Update Security PIN' : 'Enable PIN Lock'}
                </button>
                {securityPin && (
                  <button
                    type="button"
                    onClick={() => {
                      onSecurityPinChange('');
                      setPinInput('');
                      setPinStatus('PIN lock security disabled.');
                      setTimeout(() => setPinStatus(null), 3000);
                    }}
                    className="bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold py-2.5 px-5 rounded-xl text-xs cursor-pointer transition-colors"
                  >
                    Disable Lock
                  </button>
                )}
              </form>

              {pinStatus && (
                <div className={`p-3 rounded-xl border text-xs font-medium flex items-center gap-2 ${
                  pinStatus.startsWith('Error') 
                    ? 'bg-rose-50 border-rose-100 text-rose-700' 
                    : 'bg-emerald-50 border-emerald-100 text-emerald-700'
                }`}>
                  {pinStatus.startsWith('Error') ? <AlertTriangle className="w-4 h-4" /> : <CheckCircle className="w-4 h-4" />}
                  {pinStatus}
                </div>
              )}
            </div>

            <hr className="border-slate-100" />

            {/* 3. Notifications reminder simulation */}
            <div className="space-y-3">
              <label className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
                <Bell className="w-4 h-4 text-indigo-500" />
                Fintech Notifications & Reminders
              </label>
              <p className="text-xs text-slate-500">Bulk push payment schedule notifications or send automated collection reminders to outstanding borrowers.</p>
              
              <div className="flex flex-wrap gap-3 pt-1">
                <button
                  onClick={() => handleTriggerSimulatedReminder('whatsapp')}
                  className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-500 transition-colors text-white font-semibold px-4 py-2.5 rounded-xl cursor-pointer text-xs"
                >
                  <Smartphone className="w-4 h-4" />
                  Simulate WhatsApp Reminders
                </button>
                <button
                  onClick={() => handleTriggerSimulatedReminder('sms')}
                  className="flex items-center gap-2 bg-slate-800 hover:bg-slate-700 transition-colors text-white font-semibold px-4 py-2.5 rounded-xl cursor-pointer text-xs"
                >
                  <Smartphone className="w-4 h-4" />
                  Simulate SMS Reminders
                </button>
              </div>

              {simulatedReminderStatus && (
                <div className={`p-4 rounded-xl text-xs font-medium border animate-fade-in ${
                  simulatedReminderStatus.startsWith('Success') 
                    ? 'bg-emerald-50/80 border-emerald-100 text-emerald-800' 
                    : simulatedReminderStatus.startsWith('Clear')
                    ? 'bg-indigo-50 border-indigo-100 text-indigo-800'
                    : 'bg-amber-50 border-amber-100 text-amber-800'
                }`}>
                  <p>{simulatedReminderStatus}</p>
                </div>
              )}
            </div>

          </div>
        </div>

        {/* 4. One-Click Backup & Database Restore (JSON Sync) */}
        <div className="bg-white border border-slate-100 rounded-2xl p-6 shadow-xs space-y-4">
          <div className="text-left border-b border-slate-50 pb-3">
            <h3 className="font-bold text-slate-900 text-sm flex items-center gap-2">
              <Database className="w-4.5 h-4.5 text-indigo-600" />
              Backup & Database Synchronization
            </h3>
            <p className="text-xs text-slate-500">Ensure data safety. Download encrypted ledger records to your local device, or import JSON backup files instantly.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Export */}
            <div className="p-4 bg-indigo-50/20 border border-indigo-100/50 rounded-xl space-y-3 flex flex-col justify-between">
              <div className="space-y-1">
                <span className="font-bold text-slate-800 text-xs flex items-center gap-1">
                  <Download className="w-4 h-4 text-indigo-600" /> Download Local Backup
                </span>
                <p className="text-[11px] text-slate-500">Download the complete database node (members, schedules, draws, installments) as a clean JSON backup file.</p>
              </div>
              <button
                onClick={handleExportBackup}
                className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-2 rounded-lg text-xs cursor-pointer transition-colors shadow-xs"
              >
                Download Ledger JSON
              </button>
            </div>

            {/* Import */}
            <div className="p-4 bg-emerald-50/20 border border-emerald-100/50 rounded-xl space-y-3 flex flex-col justify-between">
              <div className="space-y-1">
                <span className="font-bold text-slate-800 text-xs flex items-center gap-1">
                  <Upload className="w-4 h-4 text-emerald-600" /> Restore / Synchronize
                </span>
                <p className="text-[11px] text-slate-500">Import a previously saved backup file to sync all records instantly on this sandbox device node.</p>
              </div>
              <div className="relative">
                <input
                  type="file"
                  accept=".json"
                  onChange={handleImportBackup}
                  className="hidden"
                  id="backup-file-input"
                />
                <label
                  htmlFor="backup-file-input"
                  className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-semibold py-2 rounded-lg text-xs cursor-pointer transition-colors shadow-xs block text-center"
                >
                  Select & Upload JSON
                </label>
              </div>
            </div>
          </div>
        </div>

      </div>

      {/* Signature & Authorized Panel (Right Column) */}
      <div className="space-y-6">
        
        {/* Organizer Digital Signature capture */}
        <div className="bg-white border border-slate-100 rounded-2xl p-6 shadow-xs space-y-4">
          <div className="text-left border-b border-slate-50 pb-3">
            <h3 className="font-bold text-slate-900 text-sm flex items-center gap-2">
              <Signature className="w-4.5 h-4.5 text-indigo-600" />
              Receipt Authorization Stamp
            </h3>
            <p className="text-xs text-slate-500">Draw or upload your mother's authorized organizer signature. This is automatically stamped on printable payment receipts.</p>
          </div>

          <div className="space-y-3">
            <div className="border border-slate-100 bg-indigo-50/15 rounded-xl overflow-hidden relative">
              <canvas
                ref={canvasRef}
                width={300}
                height={150}
                onMouseDown={startDrawing}
                onMouseMove={draw}
                onMouseUp={stopDrawing}
                onMouseLeave={stopDrawing}
                onTouchStart={startDrawing}
                onTouchMove={draw}
                onTouchEnd={stopDrawing}
                className="w-full cursor-crosshair bg-white"
                id="digital-signature-canvas"
              ></canvas>
              <div className="absolute top-2 right-2 text-[10px] bg-slate-800/80 text-white px-2 py-0.5 rounded-full pointer-events-none uppercase tracking-wider font-mono">
                Drawing Board
              </div>
            </div>

            <div className="flex gap-2">
              <button
                onClick={clearCanvas}
                className="flex-1 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold py-1.5 rounded-lg text-[11px] cursor-pointer transition-colors"
              >
                Clear Slate
              </button>
              <button
                onClick={saveSignature}
                className="flex-1 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-1.5 rounded-lg text-[11px] cursor-pointer transition-colors shadow-xs"
              >
                Save Stamp
              </button>
            </div>

            {signatureSaved ? (
              <div className="p-3 bg-emerald-50 border border-emerald-100 text-emerald-800 text-[11px] rounded-lg font-medium flex items-center gap-2">
                <UserCheck className="w-4.5 h-4.5 text-emerald-600" />
                Authorized Signature Stamp Saved!
              </div>
            ) : (
              <div className="p-3 bg-amber-50 border border-amber-100 text-amber-800 text-[11px] rounded-lg font-medium flex items-center gap-1.5">
                <AlertTriangle className="w-4.5 h-4.5 text-amber-600 shrink-0" />
                Draw a signature to enable printable receipts.
              </div>
            )}
          </div>
        </div>

        {/* Future Ready Fintech roadmap */}
        <div className="bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900 rounded-2xl p-6 text-white shadow-lg space-y-4 relative overflow-hidden">
          {/* Decorative radial lighting */}
          <div className="absolute bottom-0 right-0 w-24 h-24 rounded-full bg-indigo-600/20 blur-xl pointer-events-none"></div>
          
          <div className="space-y-1">
            <span className="text-[9px] font-bold text-indigo-400 tracking-wider uppercase flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5" /> FUTURE-READY NODE
            </span>
            <h3 className="font-bold text-sm">ChitMaster Pro Sync</h3>
            <p className="text-slate-300 text-[11px] leading-relaxed">
              This application has been engineered with a Repository-ready schema structure. Ready for instant transition to cloud hosting, Aadhaar validation, and real WhatsApp SDK alerts.
            </p>
          </div>

          <div className="space-y-2 border-t border-white/5 pt-3.5 text-[10px] text-slate-400">
            <div className="flex items-center gap-2">
              <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-pulse"></div>
              <span>WhatsApp Payment Reminders</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-pulse"></div>
              <span>QR Code Collections</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-pulse"></div>
              <span>Secured Fingerprint biometric auth</span>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
